services:
- name: "Communication Services"
  items:
  - name: AKHQ
    subdomain: akhq
  - name: EMQX
    subdomain: emqx
  - name: Service Registry
    subdomain: serviceregistry
- name: Asset Administration Shell Services
  items:
  - name: AAS Web GUI
    subdomain: aasgui
  - name: AAS Registry
    subdomain: aasregistry
  - name: AAS Server
    subdomain: aasserver
    href: /shells
  - name: Kibana
    subdomain: kibana
  - name: Neo4j
    subdomain: neo4j
- name: Asset Administration Shell Services v3
  items:
  - name: AAS Web GUI
    subdomain: aasgui-v3
  - name: AAS Environment
    subdomain: aas-environment
    href: /swagger-ui/index.html
  - name: AAS Registry
    subdomain: aas-registry-v3
  - name: Submodel Registry
    subdomain: sm-registry-v3
  - name: Mnestix
    subdomain: mnestix
- name: Process Control Services
  items:
  - name: Camunda
    subdomain: camunda
    href: /camunda
  - name: PPR Dashboard
    subdomain: pprdashboard
  - name: Worker Guidance System
    subdomain: wgs-client
- name: Stack Management Services
  items:
  - name: Portainer
    subdomain: portainer
- name: Observation Services
  items:
  - name: Grafana
    subdomain: grafana
