version: '3.6'

networks:
  backend_basys:
    external: true
  basys:
    internal: false

services:    

  ppr-dashboard:
    image: dfkibasys/ppr-dashboard:latest
    container_name: ppr-dashboard
    ports:
      - "8090:80"
    restart: always
    environment:
      VUE_APP_BASYS_REST_URL: "${VUE_APP_BASYS_REST_URL}"
      VUE_APP_MQTT_BROKER_URL: "${VUE_APP_MQTT_BROKER_URL}"
      VUE_APP_CAMUNDA_REST_URL: "${VUE_APP_CAMUNDA_REST_URL}"
      VUE_APP_AAS_REGISTRY_URL: "${VUE_APP_AAS_REGISTRY_URL}"
      VUE_APP_AJAX_REQUEST_DOMAIN: "${VUE_APP_AJAX_REQUEST_DOMAIN}"
      NGINX_PROXY: "${NGINX_PROXY}"

  aas-services:
    image: dfkibasys/aas-services:${VERSION}
    container_name: aas-services
    ports:
      - "4999:4999"
      - "5080:5080"
      - "5081:5081"
    volumes:
      - ./data/aas-services/config:/app/config
      - ./data/aas-services/components:/app/components
    command: -zk zookeeper:2181
    environment:
      AAS_AGGREGATOR_ACCESSIBLE_ENDPOINT: "http://${HOSTNAME}:5080"
      AAS_HOST_ACCESSIBLE_ENDPOINT: "http://${HOSTNAME}:5081"
    restart: always
    networks:
      - backend_basys
      - basys

  cc-server:
    image: dfkibasys/control-component-server:${VERSION}
    container_name: control-component-server
    ports:
      - "5082:5082" #submodel host
      - "12685:12685" #opc-ua
    volumes:
      - ./data/cc-server/config:/app/config
      - ./data/cc-server/certs:/app/certs
      - ./data/cc-server/components:/app/components
    command: -r http://aas-services:4999 -a http://aas-services:5080
    environment:
      AAS_HOST_ACCESSIBLE_ENDPOINT: "http://${HOSTNAME}:5082"
      HOSTNAME: "${HOSTNAME}"
    #restart: always
    networks:
      - backend_basys
      - basys

  service-platform:
    image: dfkibasys/service-platform:${VERSION}
    container_name: service-platform
    ports:
      - "5083:5083"
    volumes:
      - ./data/service-platform/config:/app/config
      - ./data/service-platform/components:/app/components
      - ./data/service-platform/processes:/app/processes
      - ./data/service-platform/model:/app/model
    command: -c config/ -zk zookeeper:2181 -r http://aas-services:4999 -cs tcp://activemq:61616
    environment:
      AAS_HOST_ACCESSIBLE_ENDPOINT: "http://${HOSTNAME}:5083"
    #restart: always
    networks:
      - backend_basys
      - basys
