version: '3.6'

networks:
  processcontrol:
    name: basys-processcontrol
    internal: false
  controlcomponents:
    name: basys-controlcomponents
    external: true
  proxy:
    name: basys-proxy
    external: true

services:

  camunda:
    image: camunda/camunda-bpm-platform:7.16.0
    container_name: camunda
    ports:
        - "9080:8080"
    restart: always
    environment:
      VIRTUAL_HOST: camunda.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 8080
    networks:
      - processcontrol
      - controlcomponents
      - proxy
  
  task-channel-camunda-cc:
    image: dfkibasys/task-channel-camunda-cc:${VERSION}
    container_name: task-channel-camunda-cc
    restart: always
    volumes:
      - ./data/task-channel-camunda-cc.yaml:/workspace/config/application.yaml
      - ./data/processes:/workspace/processes
    environment:
      KAFKA_BROKER_ENDPOINT: kafka:29092
      SCHEMA_REGISTRY_ENDPOINT: http://schema-registry:8081
      CAMUNDA_REST_ENDPOINT: http://camunda:8080/engine-rest
    depends_on:
      - camunda	  
    networks:
      - processcontrol

  cc-task-manager:
    image: dfkibasys/cc-task-manager:${VERSION}
    container_name: cc-task-manager
    restart: always
    volumes:
      - ./data/cc-task-manager.yaml:/workspace/config/application.yaml  
    environment:
      KAFKA_BROKER_ENDPOINT: kafka:29092
      SCHEMA_REGISTRY_ENDPOINT: http://schema-registry:8081
      AAS_REGISTRY_ENDPOINT: http://aas-registry-dotaas:8080
    networks:
      - processcontrol