version: '3.6'

networks:
  processcontrol:
    name: basys-processcontrol
    internal: false
  controlcomponents:
    name: basys-controlcomponents	
    external: true
  proxy:
    name: basys-proxy
    external: true

services:    

  camunda:
    image: camunda/camunda-bpm-platform:7.16.0
    container_name: camunda
    ports:
        - "9080:8080"
    restart: always
    environment:
      VIRTUAL_HOST:camunda.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT:8080
    networks:
      - processcontrol
      - controlcomponents
      - proxy

