version: '3.6'

networks:
  aas:
    name: basys-aas
    external: true
  communication:
    name: basys-communication
    external: true
  proxy:
    name: basys-proxy
    external: true

services:    

  risk-mitigation-recommender:
    image: dfkibasys/risk-mitigation-recommender:${VERSION}
    container_name: risk-mitigation-recommender
    depends_on:
      - aas-knowledgegraph
    ports:
     - "8089:8082"
    restart: always
    environment:
      VIRTUAL_HOST: rimirec.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 8082
      KAFKA_BROKER_ENDPOINT: kafka:29092
      NEO4J_ENDPOINT: neo4j://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: dfkibasys
    networks:
       - aas
       - communication
