version: '3.6'

networks:
  communication:
    name: basys-communication
    external: true
  aas:
    name: basys-aas
    external: true
  controlcomponents:
    name: basys-controlcomponents
    external: true
  proxy:
    name: basys-proxy
    external: true
  processcontrol:
    name: basys-processcontrol
    internal: false

services:

  camunda:
    image: camunda/camunda-bpm-platform:7.16.0
    container_name: camunda
    ports:
        - "9080:8080"
    restart: always
    environment:
      VIRTUAL_HOST: camunda.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 8080
    networks:
      - processcontrol
      - proxy
  
  task-channel-camunda-cc:
    image: dfkibasys/task-channel-camunda-cc:${VERSION}
    container_name: task-channel-camunda-cc
    restart: always
    volumes:
      - ./config/04_task-channel-camunda-cc.yml:/workspace/config/application.yml
      - ./data/processes:/workspace/processes
    environment:
      KAFKA_BROKER_ENDPOINT: kafka:29092
      SCHEMA_REGISTRY_ENDPOINT: http://schema-registry:8081
      CAMUNDA_REST_ENDPOINT: http://camunda:8080/engine-rest
    depends_on:
      - camunda
    networks:
      - communication
      - processcontrol

  task-channel-mqtt-cc:
    image: dfkibasys/task-channel-mqtt-cc:${VERSION}
    container_name: task-channel-mqtt-cc
    restart: always
    volumes:
      - ./config/04_task-channel-mqtt-cc.yml:/workspace/config/application.yml
    environment:
      KAFKA_BROKER_ENDPOINT: kafka:29092
      SCHEMA_REGISTRY_ENDPOINT: http://schema-registry:8081
      MQTT_ENDPOINT: emqx
    depends_on:
      - emqx
    networks:
      - communication
      - processcontrol

  cc-task-manager:
    image: dfkibasys/cc-task-manager:${VERSION}
    container_name: cc-task-manager
    restart: always
    volumes:
      - ./config/04_cc-task-manager.yml:/workspace/config/application.yml  
    environment:
      KAFKA_BROKER_ENDPOINT: kafka:29092
      SCHEMA_REGISTRY_ENDPOINT: http://schema-registry:8081
      AAS_REGISTRY_ENDPOINT: http://aas-registry-dotaas:8080
    extra_hosts:
      - "dockerhost:172.17.0.1"
    networks:
      - communication
      - aas
      - controlcomponents
      - processcontrol


  ppr-dashboard:
    image: dfkibasys/ppr-dashboard:dev
    container_name: ppr-dashboard
    ports:
      - "8090:80"
    environment:
      #VUE_APP_BASYS_REST_URL: "http://service-platform"
      VUE_APP_MQTT_BROKER_URL: "ws://${EXTERNAL_HOSTNAME}:8083/mqtt"
      VUE_APP_CAMUNDA_REST_URL: "http://camunda.${EXTERNAL_HOSTNAME}"
      VUE_APP_AAS_REGISTRY_URL: "http://aasregistry.${EXTERNAL_HOSTNAME}"
      VUE_APP_AJAX_REQUEST_DOMAIN: "http://pprdashboard.${EXTERNAL_HOSTNAME}/engine-rest"
      NGINX_PROXY: "http://camunda:8080/engine-rest/"
      VIRTUAL_HOST: pprdashboard.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 80
    restart: always
    networks:
      - communication
      - aas
      - processcontrol
      - proxy
