networks:
  aas:
    name: basys-aas
    internal: false
  communication:
    name: basys-communication
    external: true
  proxy:
    name: basys-proxy
    external: true

services:    
               
  aas-registry-dotaas:
    image: dfkibasys/aas-registry-dotaas-part2-kafka-mem:${AAS_REGISTRY_VERSION}
    container_name: aas-registry-dotaas
    ports:
      - "8020:8080"
    restart: always
    volumes:
      - ./config/02_aas-registry.yml:/workspace/config/application.yml
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      VIRTUAL_HOST: aasregistry.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 8080
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
       - aas
       - communication
       - proxy

  aas-server:
    image: dfkibasys/aas-server:${VERSION}
    container_name: aas-server
    ports:
     - "4001:8088"
    depends_on:
      - aas-registry-dotaas
    volumes:
      - ./config/02_aas-server.yml:/workspace/config/application.yml
      - ./data/aasx:/workspace/data
    restart: always
    environment:
      EXTERNAL_HOSTNAME: ${EXTERNAL_HOSTNAME}
      VIRTUAL_HOST: aasserver.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 8088    
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
       - aas
       - proxy

  aas-web-gui:
    image: dfkibasys/aas-web-gui:${AAS_WEBUI_VERSION}
    container_name: aas-web-gui
    ports:
      - "3300:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_REGISTRY_PATH: http://aasregistry.${EXTERNAL_HOSTNAME}
      VITE_AAS_SERVER_PATH: http://aasserver.${EXTERNAL_HOSTNAME}/shells
  #    VITE_PRIMARY_COLOR: "<primary_color>"
      VIRTUAL_HOST: aasgui.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 3000
  #  volumes:
  #    - <local_path_to_logo>:/app/src/assets/Logo
  #    - <local_path_to_plugins>:/app/src/UserPlugins
    networks:
       - aas
       - proxy
