networks:
  communication:
    name: basys-communication
    external: true
  aas:
    name: basys-aas
    external: true
  controlcomponents:
    name: basys-controlcomponents
    external: true
  proxy:
    name: basys-proxy
    external: true
  processcontrol:
    name: basys-processcontrol
    internal: false

services:

  camunda:
    image: camunda/camunda-bpm-platform:7.19.0
    container_name: camunda
    ports:
        - "9080:8080"
    restart: always
    environment:
      VIRTUAL_HOST: camunda.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 8080
    networks:
      - processcontrol
      - proxy

  task-channel-camunda-cc:
    image: dfkibasys/task-channel-camunda-cc:0.5.2-SNAPSHOT
    container_name: task-channel-camunda-cc
    restart: always
    volumes:
      - ./config/04_task-channel-camunda-cc.yml:/workspace/config/application.yml
      - ./data/processes:/workspace/processes
    environment:
      KAFKA_BROKER_ENDPOINT: kafka:29092
      SCHEMA_REGISTRY_ENDPOINT: http://schema-registry:8081
      CAMUNDA_REST_ENDPOINT: http://camunda:8080/engine-rest
    depends_on:
      - camunda
    networks:
      - communication
      - processcontrol

  task-channel-mqtt-cc:
    image: dfkibasys/task-channel-mqtt-cc:${VERSION}
    container_name: task-channel-mqtt-cc
    restart: always
    volumes:
      - ./config/04_task-channel-mqtt-cc.yml:/workspace/config/application.yml
    environment:
      KAFKA_BROKER_ENDPOINT: kafka:29092
      SCHEMA_REGISTRY_ENDPOINT: http://schema-registry:8081
      MQTT_ENDPOINT: emqx
      USE_MESSAGE_TIMESTAMP_FOR_MAPPING: false
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    networks:
      - communication
      - processcontrol

  cc-task-manager:
    image: dfkibasys/cc-task-manager:${VERSION}
    container_name: cc-task-manager
    restart: always
    volumes:
      - ./config/04_cc-task-manager.yml:/workspace/config/application.yml
    environment:
      KAFKA_BROKER_ENDPOINT: kafka:29092
      SCHEMA_REGISTRY_ENDPOINT: http://schema-registry:8081
      AAS_REGISTRY_ENDPOINT: http://aas-registry-dotaas:8080
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    extra_hosts:
      - "${EXTERNAL_HOSTNAME}:172.17.0.1"
    networks:
      - communication
      - aas
      - controlcomponents
      - processcontrol

  mqtt-kafka-bridge:
    image: dfkibasys/mqtt-kafka-bridge:${VERSION}
    container_name: mqtt-kafka-bridge
    restart: always
    #volumes:
    #  - ./config/04_mqtt-kafka-bridge.yml:/workspace/config/application.yml
    environment:
      KAFKA_BROKER_ENDPOINT: kafka:29092
      SCHEMA_REGISTRY_ENDPOINT: http://schema-registry:8081
      MQTT_BROKER_ENDPOINT: emqx
      USE_MESSAGE_TIMESTAMP_FOR_MAPPING: false
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - communication
      - processcontrol


  ppr-dashboard:
    image: dfkibasys/ppr-dashboard:${PPR_DASHBOARD_VERSION}
    container_name: ppr-dashboard
    ports:
      - "8090:8080"
    environment:
      VITE_MQTT_BROKER_URL: "ws://${EXTERNAL_HOSTNAME}:8083/mqtt"
      VITE_CAMUNDA_REST_URL: "http://camunda.${EXTERNAL_HOSTNAME}"
      VITE_AAS_REGISTRY_URL: "http://aasregistry.${EXTERNAL_HOSTNAME}"
      VITE_AJAX_REQUEST_DOMAIN: "http://pprdashboard.${EXTERNAL_HOSTNAME}/engine-rest"
      # remove the VUE_APP ENVs when we go to a new stable version
      # using both we can switch between stable and dev
      VUE_APP_MQTT_BROKER_URL: "ws://${EXTERNAL_HOSTNAME}:8083/mqtt"
      VUE_APP_CAMUNDA_REST_URL: "http://camunda.${EXTERNAL_HOSTNAME}"
      VUE_APP_AAS_REGISTRY_URL: "http://aasregistry.${EXTERNAL_HOSTNAME}"
      VUE_APP_AJAX_REQUEST_DOMAIN: "http://pprdashboard.${EXTERNAL_HOSTNAME}/engine-rest"
      VITE_MQTT_BROKER_URL: "ws://${EXTERNAL_HOSTNAME}:8083/mqtt"
      VITE_CAMUNDA_REST_URL: "http://camunda.${EXTERNAL_HOSTNAME}"
      VITE_AAS_REGISTRY_URL: "http://aasregistry.${EXTERNAL_HOSTNAME}"
      VITE_AJAX_REQUEST_DOMAIN: "http://pprdashboard.${EXTERNAL_HOSTNAME}/engine-rest"
      VITE_ENABLE_BASYSAFE_INTEGRATION: false
      NGINX_PROXY: "http://camunda:8080/engine-rest/"
      VIRTUAL_HOST: pprdashboard.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 8080
    restart: always
    depends_on:
      - camunda
    networks:
      - communication
      - aas
      - processcontrol
      - proxy

  wgs-server:
    image: dfkibasys/wgs-server:latest
    container_name: wgs-server
    environment:
      MQTT_BROKER: ws://emqx:8083/mqtt
      VIRTUAL_HOST: wgs-server.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 3002
    restart: always
    networks:
      - communication
      - processcontrol
      - proxy

  wgs-client:
    image: dfkibasys/wgs-client:latest
    container_name: wgs-client
    environment:
      SERVER_URL: http://wgs-server:3002
      SERVER_WS_URL: ws://wgs-server.${EXTERNAL_HOSTNAME}
      VIRTUAL_HOST: wgs-client.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 4200
    restart: always
    networks:
      - processcontrol
      - proxy

  wgs-management-service:
    image: dfkibasys/wgs-management-service:latest
    container_name: wgs-management-service
    environment:
      AAS_REGISTRY_ENDPOINT: http://aasregistry.${EXTERNAL_HOSTNAME}
      WGS_DASHBOARD_ENDPOINT: http://wgs-server:3002/
      NEO4J_ENDPOINT: neo4j://neo4j.${EXTERNAL_HOSTNAME}:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: dfkibasys
      KAFKA_BROKER_ENDPOINT: kafka:29092
      SCHEMA_REGISTRY_ENDPOINT: http://schema-registry:8081
      EUREKA_SERVER_ENDPOINT: service-registry/eureka
      MQTT_BROKER_ENDPOINT: emqx
    restart: always
    networks:
      - communication
      - aas
      - processcontrol

  scale-management-service:
    image: dfkibasys/scale-management-service:latest
    container_name: scale-management-service
    environment:
      AAS_REGISTRY_ENDPOINT: http://aasregistry.${EXTERNAL_HOSTNAME}
      NEO4J_ENDPOINT: neo4j://neo4j.${EXTERNAL_HOSTNAME}:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: dfkibasys
      EUREKA_SERVER_ENDPOINT: http://serviceregistry.${EXTERNAL_HOSTNAME}/eureka
      MQTT_BROKER_ENDPOINT: emqx
    restart: always
    networks:
      - communication
      - aas
      - processcontrol

