version: '3.6'

networks:
  aas:
    name: basys-aas
    internal: false
  communication:
    name: basys-communication
    external: true
  proxy:
    name: basys-proxy
    external: true

volumes:
  elasticsearch-data:
    driver: local

services:    

  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
       - aas
  
  kibana:
    image: kibana:7.14.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      VIRTUAL_HOST: kibana.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 5601
    depends_on:
      - elasticsearch
    restart: always   
    networks:
       - aas
       - proxy

  neo4j:
    image: neo4j:4.4.4-community
    container_name: neo4j
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      VIRTUAL_HOST: neo4j.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 7474
    restart: always
    networks:
      - aas
      - proxy
               
  aas-registry-dotaas:
    image: dfkibasys/aas-registry:dotaas-latest
    container_name: aas-registry-dotaas
    ports:
      - "8020:8080"
    depends_on:
      - elasticsearch
#      - kafka
    restart: always
    volumes:
      - ./data/aas-registry:/etc/config/aas-registry
    environment:
      ELASTICSEARCH_HOST_URL: elasticsearch:9200
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      VIRTUAL_HOST: aasregistry.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 8080
      SPRING_CONFIG_LOCATION: classpath:/application.yml,file:/etc/config/aas-registry/application.yaml
    networks:
       - aas
       - communication
       - proxy

  aas-registry-basyx:
    image: dfkibasys/aas-registry:1.0.2
    container_name: aas-registry-basyx
    ports: 
     - "4000:4000"
    volumes:
      - ./data/aas-registry:/usr/share/config
    restart: always
    networks:
       - aas

#  aas-server:
#    image: dfkibasys/aas-server:dotaas-latest
#    container_name: aas-server
#    ports: 
#     - "4001:4001"
#    depends_on:
#      - aas-registry-dotaas
#      - aas-registry-basyx
#    volumes:
#      - ./data/aas-server:/usr/share/config
#    restart: always
#    environment:
#      VIRTUAL_HOST: aasserver.${EXTERNAL_HOSTNAME}
#      VIRTUAL_PORT: 4001
#    networks:
#       - aas
#       - proxy

  aas-server:
    image: dfkibasys/aas-server:0.3.0-SNAPSHOT
    container_name: aas-server
    ports:
     - "4001:8088"
    depends_on:
      - aas-registry-dotaas
      - aas-registry-basyx
    volumes:
      - ./data/aas-server:/workspace/config
    restart: always
    environment:
      EXTERNAL_HOSTNAME: ${EXTERNAL_HOSTNAME}
      VIRTUAL_HOST: aasserver.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 8088
    networks:
       - aas
       - proxy
