{
 "title": "basyx",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "initiator",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "queryText": "basysafe.initiator.status" }
   ]
  },
  {
   "title": "safety light curtain",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "queryText": "basysafe.safetylightcurtain.status"
    }
   ]
  },
  {
   "title": "ack button",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "queryText": "basysafe.ackbutton.status" }
   ]
  },
  {
   "title": "press",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "queryText": "basysafe.press.status" }
   ]
  },
  {
   "title": "signal column",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "queryText": "basysafe.signalcolumn.status" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "queryText": "basysafe.signalcolumn.status" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "queryText": "basysafe.signalcolumn.status" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "queryText": "basysafe.signalcolumn.status" }
   ]
  },
  {
   "title": "EStop",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "targets": [
    { "queryText": "basysafe.estopbutton.status" }
   ]
  },
  {
   "title": "signal column",
   "type": "gauge",
   "gridPos": { "h": 24, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "signal column",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "press ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "queryText": "basysafe.press.status" }
   ]
  },
  {
   "title": "signal column",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "queryText": "basysafe.signalcolumn.status" }
   ]
  },
  {
   "title": "Latest EStop status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "queryText": "basysafe.estopbutton.status" }
   ]
  }
 ]
}