basys:
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12687
    httpsPort: 8443
  controlcomponent:
    id: drone_1
    name: Drone-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.drone.opmodes
    executionMode: SIMULATE
    auto:
      disableExecutionModeChange: false
      disableOccupationCheck: false
      service:
        implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.drone.service.DroneServiceImpl
        connectionString: tcp://10.2.10.1:1883
        droneInspectionServiceEndpoint: http://10.2.0.18:5000
        mqttUsername: "drone_control_component"
        mqttPassword: SECRET
    simulate:
      disableExecutionModeChange: true
      disableOccupationCheck: true
