basys:
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12686
    httpsPort: 8443
  controlcomponent:
    id: ur10_1
    name: UR10-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.ur.opmodes
    initialExecutionMode: SIMULATE
    executionModes:
      auto:
        executionModeChangeDisabled: false
        occupationCheckDisabled: false
        service:
          implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.ur.service.UrServiceImplRPC
          connectionString: http://10.2.1.16:8081
      simulate:
        executionModeChangeDisabled: true
        occupationCheckDisabled: true
        service:
          implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.ur.service.UrServiceImplROS
          connectionString: ws://basys-lnv-1.mrk40.dfki.lan:9100
          properties:
            movSymServerName: /movsym/ur10_1
            movSymActionName: /simrk40_msgs/MoveToSymbolicPositionAction
            ppSymServerName: /ppsym/ur10_1
            ppSymActionName: /simrk40_msgs/PickAndPlaceSymbolicAction
            pickSymServerName: /picksym/ur10_1
            pickSymActionName: /simrk40_msgs/PickSymbolicAction
            placeSymServerName: /placesym/ur10_1
            placeSymActionName: /simrk40_msgs/PlaceSymbolicAction
            joinSymServerName: /joinsym/ur10_1
            joinSymActionName: /simrk40_msgs/JoinSymbolicAction
