basys:
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12686
    httpsPort: 8443
  controlcomponent:
    id: ur10_1
    name: UR10-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.ur.opmodes
    executionMode: SIMULATE
    auto:
      disableExecutionModeChange: false
      disableOccupationCheck: false
      service:
        implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.ur.service.UrServiceImplRPC
        connectionString: http://10.2.1.16:8081
    simulate:
      disableExecutionModeChange: true
      disableOccupationCheck: true
