apiVersion: 1
groups:
    - orgId: 1
      name: 30s-evalutation
      folder: alerts
      interval: 30s
      rules:
        - uid: d0525cac-5201-4c9f-8ff3-012dc4490f5f
          title: Disk Space Usage over 70%
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: SNpaCLr4z
              model:
                datasource:
                    type: prometheus
                    uid: SNpaCLr4z
                editorMode: code
                expr: 100 - ((node_filesystem_avail_bytes{instance="node-exporter:9100",job="node",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance="node-exporter:9100",job="node",device!~'rootfs'})
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 70
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations: {}
          labels: {}
          isPaused: false
