version: '3.6'
    
networks:
  admin:
    name: basys-admin
    internal: false	

services:      
  portainer:
    image: portainer/portainer-ce:2.11.0
    container_name: portainer
    restart: always
    ports:
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - admin